name: Trigger branch merge

on:
  workflow_call:
    inputs:
      from_branch:
        type: string
        required: true
      to_branch:
        type: string
        required: true

jobs:
  Merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Merge ${{ inputs.from_branch }} to ${{ inputs.to_branch }}
        run: |
          git fetch origin ${{ inputs.to_branch }}
          git checkout ${{ inputs.to_branch }}
          git merge ${{ inputs.from_branch }}
          git push -f
