
name: test

on:
  push:
    branches:
      - "main"
env:  
  MY_REPO: https://certyfreak:${{secrets.GITHUB_TOKEN}}@github.com/certyfreak/ci-cd.git

  MY_BRANCH: main

  MASTER_REPO: https://github.com/certyfreak/ci-cd.git

  MASTER_BRANCH: production

jobs:
  add:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - run: |
          ls
