name: Trigger to production
on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Deploy to production => qa -> production
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - run: |
          git fetch origin production
          git checkout production
          git merge main
          git push -f
